-- Treatment packages for Apollo (Cardiology, Orthopedics, Neurology)
INSERT INTO treatment_packages (hospital_id, name, category, description, price, currency, duration_days, recovery_days, is_active, popularity_score, inclusions, exclusions) VALUES
('99a298b6-2e18-4732-8692-d4ef2c050436', 'Cardiac Bypass Surgery Package', 'Cardiology', 'Comprehensive CABG surgery including pre-op evaluation, surgery, ICU stay, and post-operative care by world-class cardiac surgeons.', 7500, 'USD', 10, 14, true, 92, '["Pre-operative tests","Surgery charges","ICU stay (3 days)","Ward stay (7 days)","Medications","Post-op consultations"]', '["Travel expenses","Visa processing","Hotel accommodation"]'),
('99a298b6-2e18-4732-8692-d4ef2c050436', 'Total Knee Replacement', 'Orthopedics', 'Advanced knee replacement surgery using imported prosthetics with physiotherapy and rehabilitation included.', 6000, 'USD', 8, 21, true, 88, '["Surgery charges","Implant cost","Physiotherapy (10 sessions)","Hospital stay","Medications"]', '["Travel expenses","Extended rehabilitation"]'),
('99a298b6-2e18-4732-8692-d4ef2c050436', 'Brain Tumor Surgery', 'Neurology', 'Minimally invasive neurosurgery for brain tumors with advanced imaging and navigation technology.', 12000, 'USD', 14, 30, true, 75, '["MRI & CT scans","Surgery charges","ICU stay","Medications","Follow-up consultations"]', '["Chemotherapy","Radiation therapy","Travel"]');

-- Treatment packages for Srikara (Oncology, Neurology)
INSERT INTO treatment_packages (hospital_id, name, category, description, price, currency, duration_days, recovery_days, is_active, popularity_score, inclusions, exclusions) VALUES
('cbc17b78-21bc-4f8f-a805-a758b2ae80c1', 'Cancer Treatment Package', 'Oncology', 'Comprehensive cancer treatment including diagnosis, chemotherapy cycles, and regular monitoring by oncology specialists.', 8500, 'USD', 30, 60, true, 85, '["Diagnostic workup","Chemotherapy (6 cycles)","Medications","Specialist consultations","Lab tests"]', '["Radiation therapy","Surgery if needed","Travel expenses"]'),
('cbc17b78-21bc-4f8f-a805-a758b2ae80c1', 'Spine Surgery Package', 'Neurology', 'Advanced spinal fusion surgery with post-operative physiotherapy and rehabilitation support.', 9000, 'USD', 12, 28, true, 78, '["Surgery charges","Implants","ICU stay","Physiotherapy","Medications"]', '["Extended rehab","Travel","Accommodation"]');

-- Treatment packages for A1 Hospital (Dental, Ophthalmology)
INSERT INTO treatment_packages (hospital_id, name, category, description, price, currency, duration_days, recovery_days, is_active, popularity_score, inclusions, exclusions) VALUES
('01e0661c-0a61-4eec-96ed-935fdaf19029', 'Full Mouth Dental Implants', 'Dental Care', 'Complete dental restoration with premium titanium implants, ceramic crowns, and comprehensive aftercare.', 3500, 'USD', 7, 7, true, 90, '["Consultation","X-rays & CT scan","Implant placement","Ceramic crowns","Follow-up visits"]', '["Bone grafting if needed","Travel","Hotel stay"]'),
('01e0661c-0a61-4eec-96ed-935fdaf19029', 'LASIK Eye Surgery', 'Ophthalmology', 'Blade-free LASIK with latest femtosecond laser technology for precise vision correction.', 1200, 'USD', 2, 5, true, 95, '["Pre-operative assessment","Surgery (both eyes)","Protective eyewear","Medications","Follow-up visits"]', '["Travel expenses","Accommodation"]');

-- Treatment packages for Fortis Memorial (Cardiology, Orthopedics)
INSERT INTO treatment_packages (hospital_id, name, category, description, price, currency, duration_days, recovery_days, is_active, popularity_score, inclusions, exclusions) VALUES
('f0efb79b-992f-42e1-80f2-9d1b7abcba16', 'Robotic Heart Surgery', 'Cardiology', 'Cutting-edge robotic-assisted cardiac surgery with minimal scarring and faster recovery times.', 15000, 'USD', 7, 14, true, 82, '["Robotic surgery charges","ICU stay","Medications","Cardiac rehabilitation","Follow-up echocardiogram"]', '["Travel","Extended cardiac rehab","Accommodation"]'),
('f0efb79b-992f-42e1-80f2-9d1b7abcba16', 'Hip Replacement Surgery', 'Orthopedics', 'Total hip replacement with premium ceramic-on-ceramic prosthesis and comprehensive physiotherapy program.', 8500, 'USD', 10, 21, true, 86, '["Surgery charges","Imported prosthesis","Hospital stay","Physiotherapy (15 sessions)","Medications"]', '["Travel expenses","Extended rehabilitation"]');

-- Treatment packages for Medanta Medicity (Oncology, Cardiology)
INSERT INTO treatment_packages (hospital_id, name, category, description, price, currency, duration_days, recovery_days, is_active, popularity_score, inclusions, exclusions) VALUES
('e0a57a1d-a16f-4439-b5e6-a9b4fbf4dc5c', 'Liver Transplant Package', 'Oncology', 'Complete liver transplant program including donor evaluation, transplant surgery, ICU, and long-term follow-up care.', 35000, 'USD', 30, 90, true, 80, '["Donor evaluation","Transplant surgery","ICU stay (7 days)","Ward stay","Immunosuppressants (3 months)","Follow-up consultations"]', '["Donor travel expenses","Long-term medications","Accommodation"]'),
('e0a57a1d-a16f-4439-b5e6-a9b4fbf4dc5c', 'Heart Valve Replacement', 'Cardiology', 'Minimally invasive heart valve replacement with biological or mechanical valve options.', 11000, 'USD', 10, 21, true, 87, '["Pre-op assessment","Surgery charges","Valve implant","ICU stay","Cardiac rehabilitation"]', '["Travel","Extended cardiac rehab","Accommodation"]');

-- Treatment packages for Max Super Specialty (General Surgery, Oncology)
INSERT INTO treatment_packages (hospital_id, name, category, description, price, currency, duration_days, recovery_days, is_active, popularity_score, inclusions, exclusions) VALUES
('f4d0c82a-a013-49dd-936f-9137bacdc1d0', 'Bariatric Surgery Package', 'General Surgery', 'Laparoscopic sleeve gastrectomy with comprehensive pre and post-operative dietary counseling.', 5500, 'USD', 5, 14, true, 91, '["Pre-op assessment","Laparoscopic surgery","Hospital stay","Nutritionist consultations","Follow-up visits"]', '["Travel expenses","Post-surgery supplements","Accommodation"]'),
('f4d0c82a-a013-49dd-936f-9137bacdc1d0', 'Prostate Cancer Treatment', 'Oncology', 'Robotic-assisted prostatectomy with precision surgery and rapid recovery protocol.', 9500, 'USD', 7, 21, true, 76, '["Diagnostic workup","Robotic surgery","Hospital stay","Medications","Follow-up PSA tests"]', '["Radiation therapy","Hormone therapy","Travel"]');