// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://slgzisdvfsruqlhtafvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsZ3ppc2R2ZnNydXFsaHRhZnZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3NTYwMDMsImV4cCI6MjA3NTMzMjAwM30.5z4HV_pNk7R6C0B3HCyRYQss1mCv45oj0UNJxSQ_QeI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});